name: Clang Format
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  clang-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 1
    if: |
      contains(github.event.pull_request.body, 'FORCE_TEST_ACTIONS')
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run : |
          sudo apt-get update && sudo apt-get install -yq clang clang-format
      - name: Run clang-format
        run: clang-format --dry-run -Werror --verbose \
          $(git diff --name-only origin/main HEAD -- '*.cc' '*.hh' '*.hpp')
