# This workflow will run integration tests.

name: Integration Tests
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  run_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run : |
          sudo apt-get update && sudo apt-get install -yq clang clang-format
      - name: Build everything
        run: |
          cd cxx && bazel build tests:all
      - name: Test C++
        run: |
          ./bazel-bin/tests/test_hirm_animals && \
          ./bazel-bin/tests/test_irm_two_relations && \
          ./bazel-bin/tests/test_misc
